"use client";
import React, { useCallback, useState } from "react";
import dynamic from "next/dynamic";
import { ReactFlow, useReactFlow, ReactFlowProvider } from "@xyflow/react";
import { useEditorStore, type EditorNode, type NodeType } from "@/lib/stores/editor-store";
import { EditorToolbar } from "@/components/editor/EditorToolbar";
import { NodeEditPanel } from "@/components/editor/NodeEditPanel";
import { X } from "lucide-react";

const MapCanvas = dynamic(
  () => import("@/components/editor/MapCanvas").then((m) => m.MapCanvas),
  { ssr: false, loading: () => (
    <div className="flex h-full w-full items-center justify-center bg-[var(--color-background)]">
      <span className="text-sm text-[var(--color-muted-foreground)]">Loading canvas…</span>
    </div>
  )}
);

// Captures the ReactFlow instance for toolbar controls
function FlowBridge({ children, onInstance }: { children: React.ReactNode; onInstance: (i: ReturnType<typeof useReactFlow>) => void }) {
  const instance = useReactFlow();
  React.useEffect(() => { onInstance(instance); }, [instance]); // eslint-disable-line react-hooks/exhaustive-deps
  return <>{children}</>;
}

export default function EditorPage() {
  const { nodes, edges, addNode } = useEditorStore();
  const [editingNodeId, setEditingNodeId] = useState<string | null>(null);
  const [showPanel, setShowPanel] = useState(false);
  const [rfInstance, setRfInstance] = useState<ReturnType<typeof useReactFlow> | null>(null);

  const handleAddNode = useCallback((type: NodeType) => {
    const n: EditorNode = {
      id: `node_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      name: `New ${type}`, type,
      description: "", tags: [],
      position: { x: 100 + Math.random() * 400, y: 100 + Math.random() * 300 },
    };
    addNode(n);
  }, [addNode]);

  const handleNodeDoubleClick = useCallback((nodeId: string) => {
    setEditingNodeId(nodeId);
    setShowPanel(true);
  }, []);

  const zoomIn = useCallback(() => rfInstance?.zoomIn({ duration: 200 }), [rfInstance]);
  const zoomOut = useCallback(() => rfInstance?.zoomOut({ duration: 200 }), [rfInstance]);
  const fitView = useCallback(() => rfInstance?.fitView({ padding: 0.3, duration: 400 }), [rfInstance]);

  const handleAiGenerate = useCallback(() => {
    const samples: EditorNode[] = [
      { id: `ai_${Date.now()}_a`, name: "AI Gene Alpha", type: "Gene", description: "Generated by AI", tags: ["ai"], position: { x: 300, y: 50 } },
      { id: `ai_${Date.now()}_b`, name: "AI Capsule Beta", type: "Capsule", description: "Generated capsule", tags: ["ai"], position: { x: 500, y: 200 } },
    ];
    samples.forEach(addNode);
  }, [addNode]);

  const closePanel = useCallback(() => { setShowPanel(false); setEditingNodeId(null); }, []);
  const isEmpty = nodes.length === 0 && edges.length === 0;

  return (
    <ReactFlowProvider>
      <FlowBridge onInstance={setRfInstance}>
        <div className="relative flex h-screen w-screen flex-col overflow-hidden bg-[var(--color-background)]">
          <header className="relative z-10 flex items-center gap-3 border-b border-[var(--color-border)] bg-[var(--color-background)]/80 backdrop-blur-sm px-4 py-2.5">
            <span className="text-sm font-bold text-[var(--color-foreground)]">my-evo</span>
            <span className="text-xs text-[var(--color-muted-foreground)]">/ editor</span>
            <div className="flex-1">
              <EditorToolbar onZoomIn={zoomIn} onZoomOut={zoomOut} onFitView={fitView} onAddNode={handleAddNode} onAiGenerate={handleAiGenerate} />
            </div>
          </header>

          <div className="relative flex flex-1 overflow-hidden">
            <div className="flex-1 relative">
              <MapCanvas onNodeDoubleClick={handleNodeDoubleClick} />
              {isEmpty && (
                <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
                  <div className="text-center">
                    <div className="mb-4 text-5xl">🧬</div>
                    <p className="text-sm font-medium text-[var(--color-foreground)]">Start building your knowledge map</p>
                    <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">Click <b>Add</b> to insert a node, or <b>AI</b> to generate</p>
                  </div>
                </div>
              )}
            </div>

            <div className={`w-80 flex-shrink-0 border-l border-[var(--color-border)] bg-[var(--color-background)] transition-all duration-200 ${showPanel ? "translate-x-0" : "translate-x-full pointer-events-none"}`}>
              {showPanel && editingNodeId !== null && (
                <div className="flex h-full flex-col">
                  <div className="flex items-center justify-between border-b border-[var(--color-border)] px-4 py-3">
                    <span className="text-xs font-semibold text-[var(--color-muted-foreground)]">Node Properties</span>
                    <button onClick={closePanel} className="rounded-md p-1 text-[var(--color-muted-foreground)] hover:bg-[var(--color-surface-muted)]">
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                  <div className="flex-1 overflow-y-auto">
                    <NodeEditPanel nodeId={editingNodeId} onClose={closePanel} />
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="flex h-7 items-center gap-4 border-t border-[var(--color-border)] bg-[var(--color-surface-muted)] px-4 text-[10px] text-[var(--color-muted-foreground)]">
            <span>{nodes.length} nodes</span>
            <span>{edges.length} edges</span>
            <span className="ml-auto">React Flow Canvas · my-evo</span>
          </div>
        </div>
      </FlowBridge>
    </ReactFlowProvider>
  );
}
